# Generated by Django 5.0.4 on 2024-05-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
        ('Course', '0009_videocourseobject_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritevideocourse',
            name='video_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.videocourse', verbose_name='دوره ویدئویی'),
        ),
    ]
