# Generated by Django 5.0.4 on 2024-04-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='owner',
            new_name='user',
        ),
    ]
