# Generated by Django 5.0.4 on 2024-04-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('PV', 'شخصی'), ('PU', 'عمومی')], default='PU', max_length=2, verbose_name='حالت اکانت'),
        ),
    ]
