# Generated by Django 5.0.4 on 2024-04-18 13:41

import django_ckeditor_5.fields
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_customuser_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('YN', 'آره و نه'), ('AN', 'اطلاعیه')], default='AN', max_length=2, verbose_name='نوع اعلان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='has_been_read',
            field=models.BooleanField(default=False, verbose_name='آیا خوانده شده؟'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Account/Notification/image', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='mode',
            field=models.CharField(choices=[('S', 'امن'), ('C', 'هشدار'), ('D', 'خطر')], max_length=1, verbose_name='مود اعلان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100, verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربران'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='visibility',
            field=models.CharField(choices=[('G', 'عمومی'), ('P', 'شخصی')], max_length=1, verbose_name='وضعیت مشاهده'),
        ),
    ]
