# Generated by Django 5.0.4 on 2024-04-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_notification_type_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تصویر'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='mode',
            field=models.CharField(choices=[('S', 'موفقیت (سبز)'), ('C', 'هشدار (نارنجی)'), ('D', 'خطر (قرمز)')], max_length=1, verbose_name='مود اعلان'),
        ),
    ]
