# Generated by Django 5.0.4 on 2024-04-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_notification_image_link_alter_notification_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='does_user_have_image',
            field=models.BooleanField(default=False, editable=False, verbose_name='آیا کاربر تصویر دارد؟'),
        ),
    ]
