# Generated by Django 5.0.4 on 2024-04-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_customuserboughtcourse_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserBoughtCourse',
        ),
    ]
