# Generated by Django 5.0.4 on 2024-04-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_wallet_usage_wallet_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='difference',
            field=models.IntegerField(default=0, editable=False, verbose_name='میزان تفاوت'),
        ),
    ]
