# Generated by Django 5.0.4 on 2024-04-18 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_notification_does_user_have_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='follower',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='فالور'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='following',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='فالوینگ'),
            preserve_default=False,
        ),
    ]
