# Generated by Django 5.0.4 on 2024-04-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_wallet_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='fund',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='سرمایه'),
        ),
    ]
