# Generated by Django 5.0.4 on 2024-04-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_notification_follower_notification_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='does_user_have_image',
        ),
    ]
