# Generated by Django 5.0.4 on 2024-04-19 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_remove_notification_does_user_have_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='follower',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='فالور'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='following',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='فالوینگ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('FO', 'فالو'), ('AN', 'اطلاعیه')], default='AN', max_length=2, verbose_name='نوع اعلان'),
        ),
    ]
