# Generated by Django 5.0.4 on 2024-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='fund',
            field=models.PositiveBigIntegerField(default=0, verbose_name='سرمایه'),
        ),
    ]
