# Generated by Django 5.0.4 on 2024-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_wallet_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('R', 'ثبت نام'), ('F', 'فراموشی رمز عبور'), ('D', 'حذف حساب کاربری'), ('UPH', 'به\u200c\u200cروز\u200c\u200cرسانی شماره تلفن')], max_length=3),
        ),
    ]
