# Generated by Django 5.0.4 on 2024-04-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_alter_otp_otp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(blank=True, choices=[('R', 'ثبت نام'), ('F', 'فراموشی رمز عبور'), ('D', 'حذف حساب کاربری'), ('UPH', 'به\u200c\u200cروز\u200c\u200cرسانی شماره تلفن')], max_length=3, null=True, verbose_name='نوع رمز یکبار مصرف'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='sms_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='کد تایید'),
        ),
    ]
