# Generated by Django 5.0.4 on 2024-04-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_post_uuid_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
    ]
