# Generated by Django 5.0.4 on 2024-04-25 04:43

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveSmallIntegerField(default=0, verbose_name='مبلغ')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('pdf_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Course.pdfcourse', verbose_name='دوره پی\u200cدی\u200cافی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Course.videocourse', verbose_name='دوره ویدئویی')),
            ],
            options={
                'verbose_name': 'دوره خریداری شده',
                'verbose_name_plural': 'دوره\u200cهای خریداری شده',
                'db_table': 'cart__bought_course',
            },
        ),
    ]
