# Generated by Django 5.0.4 on 2024-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='holding_status',
            field=models.CharField(choices=[('NS', 'هنوز شروع نشده'), ('IP', 'در حال برگزاری'), ('F', 'به اتمام رسیده')], default='NS', max_length=2, verbose_name='وضعیت دوره'),
        ),
    ]
