# Generated by Django 5.0.4 on 2024-04-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='generation_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='نسل چندم؟'),
        ),
    ]
