# Generated by Django 5.0.4 on 2024-05-06 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfexamtimer',
            name='pdf_exam',
        ),
        migrations.AddField(
            model_name='pdfexamtimer',
            name='pdf_exam_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.pdfexamdetail'),
        ),
    ]
