# Generated by Django 5.0.4 on 2024-04-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_boughtcourse'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boughtcourse',
            table='course__bought_course',
        ),
    ]
