# Generated by Django 5.0.4 on 2024-05-03 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_pdfcourse_coefficient_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='coefficient_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='یک عدد صحیح بین 1 تا 4', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='ضریب'),
        ),
        migrations.AlterField(
            model_name='pdfcourse',
            name='coefficient_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='یک عدد صحیح بین 1 تا 4', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='ضریب'),
        ),
    ]
