# Generated by Django 5.0.4 on 2024-04-25 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_alter_boughtcourse_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtcourse',
            name='cost',
        ),
    ]
