# Generated by Django 5.0.4 on 2024-05-07 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_remove_pdfexamdetail_question_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfexamtimer',
            name='pdf_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.pdfexam', verbose_name='آزمون پی\u200c\u200cدی\u200c\u200cافی'),
        ),
    ]
