# Generated by Django 5.0.4 on 2024-05-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_videocourse_coefficient_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfcourseobject',
            name='session',
        ),
    ]
