# Generated by Django 5.0.4 on 2024-05-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_remove_pdfcourseobject_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfcourseobject',
            options={'verbose_name': 'قسمت  دوره پی\u200cدی\u200cافی', 'verbose_name_plural': 'قسمت\u200c\u200cهای دوره پی\u200cدی\u200cافی'},
        ),
        migrations.AlterModelOptions(
            name='videocourseobject',
            options={'verbose_name': 'قسمت  دوره ویدئویی', 'verbose_name_plural': 'قسمت\u200c\u200cهای دوره ویدئویی'},
        ),
        migrations.RemoveField(
            model_name='videocourseobject',
            name='session',
        ),
    ]
