# Generated by Django 5.0.4 on 2024-04-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_remove_boughtcourse_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtcourse',
            name='cost',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='مبلغ'),
        ),
    ]
