# Generated by Django 5.0.4 on 2024-05-07 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_alter_pdfexamtimer_pdf_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField(verbose_name='درصد')),
                ('pdf_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.pdfexam', verbose_name='آزمون پی\u200c\u200cدی\u200c\u200cافی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نتیجه آزمون پی\u200c\u200cدی\u200c\u200cافی',
                'verbose_name_plural': 'نتایج آزمون پی\u200c\u200cدی\u200c\u200cافی',
                'db_table': 'course__pdf_exam_result',
            },
        ),
    ]
