# Generated by Django 5.0.4 on 2024-04-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی\u200cها'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='course__category',
        ),
    ]
