# Generated by Django 5.0.4 on 2024-05-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_pdfexamresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfexamdetail',
            name='correct_answer',
            field=models.CharField(help_text='متن یکی از فیلد\u200c\u200cهای بالا', max_length=200, verbose_name='گزینه صحیح'),
        ),
    ]
