# Generated by Django 5.0.4 on 2024-05-04 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_alter_pdfcourse_introduction_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfcourse',
            name='introduction_pdf',
            field=models.FileField(help_text='فقط PDF', upload_to='Course/PDFCourse/introduction_pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='پی\u200cدی\u200cاف مقدمه'),
        ),
        migrations.AlterField(
            model_name='pdfcourseobject',
            name='pdf_file',
            field=models.FileField(help_text='فقط PDF', upload_to='Course/PDFCourse/tutorials', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='فایل پی\u200cدی\u200cاف'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='introduction_video',
            field=models.FileField(help_text='فرمت\u200c\u200cهای mp4 و mkv', upload_to='Course/VideoCourse/introduction_video', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv'])], verbose_name='فیلم مقدمه'),
        ),
        migrations.AlterField(
            model_name='videocourseobject',
            name='video_file',
            field=models.FileField(help_text='فرمت\u200c\u200cهای mp4 و mkv', upload_to='Course/VideoCourse/tutorials', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv'])], verbose_name='فایل ویدئو'),
        ),
    ]
