# Generated by Django 5.0.4 on 2024-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_alter_pdfexamdetail_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfexamresult',
            name='false_answers_count',
            field=models.SmallIntegerField(default=0, verbose_name='تعداد پاسخ\u200c\u200cهای غلط'),
        ),
        migrations.AddField(
            model_name='pdfexamresult',
            name='true_answers_count',
            field=models.SmallIntegerField(default=0, verbose_name='تعداد پاسخ\u200c\u200cهای صحیح'),
        ),
    ]
