# Generated by Django 5.0.4 on 2024-05-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcourseobject',
            name='download_file_name',
            field=models.CharField(default=1, max_length=50, verbose_name='اسم فایل دانلودی'),
            preserve_default=False,
        ),
    ]
