# Generated by Django 5.0.4 on 2024-05-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_alter_pdfcourse_introduction_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcourseobject',
            name='session',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='قسمت'),
        ),
        migrations.AlterField(
            model_name='pdfcourseobject',
            name='download_file_name',
            field=models.CharField(help_text='فقط حروف انگلیسی و ارقام لاتین', max_length=50, verbose_name='نام فایل دانلودی'),
        ),
        migrations.AlterField(
            model_name='videocourseobject',
            name='download_file_name',
            field=models.CharField(help_text='فقط حروف انگلیسی و ارقام لاتین', max_length=50, verbose_name='نام فایل دانلودی'),
        ),
    ]
