# Generated by Django 5.0.4 on 2024-05-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_pdfcourseobject_download_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcourseobject',
            name='session',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='قسمت'),
        ),
    ]
