# Generated by Django 5.0.4 on 2024-05-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_pdfexamresult_result_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfexamresult',
            name='none_answers_count',
            field=models.SmallIntegerField(default=0, verbose_name='تعداد پاسخ\u200c\u200cهای جواب'),
        ),
    ]
