# Generated by Django 5.0.4 on 2024-05-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_pdfcourseobject_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfcourse',
            name='total_pages',
        ),
        migrations.AddField(
            model_name='pdfcourseobject',
            name='has_changed_total_pages',
            field=models.BooleanField(default=False, help_text='در صورت فعال بودن، دیگر به تعداد صفحات کل دوره افزوده نخواهد شد.', verbose_name='آیا صفحات کل تغییر یافته؟'),
        ),
        migrations.AlterField(
            model_name='pdfcourseobject',
            name='download_file_name',
            field=models.CharField(help_text='ققط انگلیسی', max_length=50, verbose_name='نام فایل دانلودی'),
        ),
    ]
