# Generated by Django 5.0.4 on 2024-05-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_pdfcourseobject_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourseobject',
            name='session',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='قسمت'),
        ),
    ]
