# Generated by Django 5.0.4 on 2024-04-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_boughtcourse_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtcourse',
            name='cost',
        ),
    ]
