# Generated by Django 5.0.4 on 2024-05-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0009_remove_pdfcourse_total_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfcourseobject',
            name='has_changed_total_pages',
        ),
    ]
