# Generated by Django 5.0.4 on 2024-05-02 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_remove_pdfcourseobject_has_changed_total_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfcourse',
            name='total_seasons',
        ),
        migrations.RemoveField(
            model_name='pdfcourse',
            name='total_sessions',
        ),
    ]
