# Generated by Django 5.0.4 on 2024-04-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_boughtcourse_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtcourse',
            name='cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت خرید'),
        ),
        migrations.AlterField(
            model_name='pdfcourse',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='pdfcourse',
            name='price_after_discount',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='قیمت بعد از تخفیف'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='price_after_discount',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='قیمت بعد از تخفیف'),
        ),
    ]
