# Generated by Django 5.0.4 on 2024-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_alter_boughtcourse_cost_alter_pdfcourse_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtcourse',
            name='cost',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='قیمت خرید'),
        ),
    ]
