# Generated by Django 5.0.4 on 2024-05-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_remove_pdfcourse_total_seasons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfcourse',
            name='what_we_will_learn',
            field=models.TextField(max_length=250, verbose_name='چی یاد میگیریم؟'),
        ),
    ]
