# Generated by Django 5.0.4 on 2024-05-09 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_pdfexamresult_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoexam',
            name='video_course_season',
        ),
        migrations.RemoveField(
            model_name='videoexamdetail',
            name='video_exam',
        ),
        migrations.CreateModel(
            name='CurrentPDFExamParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شرکت کننده فعلی آزمون پی\u200c\u200cدی\u200c\u200cافی',
                'verbose_name_plural': 'شرکت کنندگان فعلی آزمون پی\u200c\u200cدی\u200c\u200cافی',
                'db_table': 'course__pdf_exam_participation',
            },
        ),
        migrations.DeleteModel(
            name='PDFExamFinalAnswer',
        ),
        migrations.DeleteModel(
            name='VideoExam',
        ),
        migrations.DeleteModel(
            name='VideoExamDetail',
        ),
    ]
