# Generated by Django 5.0.4 on 2024-05-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_alter_pdfcourse_what_we_will_learn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocourse',
            name='total_duration',
        ),
        migrations.RemoveField(
            model_name='videocourse',
            name='total_seasons',
        ),
        migrations.RemoveField(
            model_name='videocourse',
            name='total_sessions',
        ),
    ]
