# Generated by Django 5.0.4 on 2024-05-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0014_pdfcourseobjectdownloadedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='what_we_will_learn',
            field=models.TextField(max_length=250, verbose_name='چی یاد میگیریم؟'),
        ),
    ]
