# Generated by Django 5.0.4 on 2024-05-09 10:33

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0014_currentpdfexamparticipation_pdf_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='نام آزمون')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('duration', models.DurationField(default=900, help_text='به ثانیه (پیش\u200c\u200cفرض: 15 دقیقه)', verbose_name='مدت زمان آزمون')),
                ('video_course_season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Course.videocourseseason', verbose_name='فصل آزمون ویدئویی')),
            ],
            options={
                'verbose_name': 'آزمون ویدئویی',
                'verbose_name_plural': 'آزمون\u200c\u200cهای ویدئویی',
                'db_table': 'course__video_exam',
            },
        ),
        migrations.CreateModel(
            name='VideoExamDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='صورت سوال')),
                ('answer_1', models.CharField(max_length=200, verbose_name='گزینه 1')),
                ('answer_2', models.CharField(max_length=200, verbose_name='گزینه 2')),
                ('answer_3', models.CharField(max_length=200, verbose_name='گزینه 3')),
                ('answer_4', models.CharField(max_length=200, verbose_name='گزینه 4')),
                ('correct_answer', models.CharField(help_text='متن یکی از فیلد\u200c\u200cهای بالا', max_length=200, verbose_name='گزینه صحیح')),
                ('video_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.videoexam', verbose_name='آزمون ویدئویی')),
            ],
            options={
                'verbose_name': 'جواب آزمون ویدئویی',
                'verbose_name_plural': 'جواب\u200c\u200cهای آزمون ویدئویی',
                'db_table': 'course__video_exam_detail',
            },
        ),
        migrations.CreateModel(
            name='VideoExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(verbose_name='درصد')),
                ('true_answers_count', models.SmallIntegerField(default=0, verbose_name='تعداد پاسخ\u200c\u200cهای صحیح')),
                ('false_answers_count', models.SmallIntegerField(default=0, verbose_name='تعداد پاسخ\u200c\u200cهای غلط')),
                ('none_answers_count', models.SmallIntegerField(default=0, verbose_name='تعداد پاسخ\u200c\u200cهای جواب')),
                ('result_status', models.CharField(choices=[('E', 'عالی'), ('G', 'عالی'), ('N', 'معمولی'), ('B', 'بد')], max_length=1, verbose_name='وضعیت نتیجه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.videoexam', verbose_name='آزمون ویدئویی')),
            ],
            options={
                'verbose_name': 'نتیجه آزمون ویدئویی',
                'verbose_name_plural': 'نتایج آزمون ویدئویی',
                'db_table': 'course__video_exam_result',
            },
        ),
        migrations.CreateModel(
            name='VideoExamTempAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='صورت سوال')),
                ('selected_answer', models.CharField(max_length=200, verbose_name='گزینه انتخاب شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video_exam_detail', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='temp_answers', to='Course.videoexamdetail', verbose_name='آزمون ویدئویی')),
            ],
            options={
                'verbose_name': 'پاسخ موقت آزمون ویدئویی',
                'verbose_name_plural': 'پاسخ\u200c\u200cهای موقت آزمون ویدئویی',
                'db_table': 'course__video_temp_answer',
            },
        ),
        migrations.CreateModel(
            name='VideoExamTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='شروع شده در تاریخ')),
                ('ends_at', models.DateTimeField(verbose_name='پایان در تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('video_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.videoexam', verbose_name='آزمون ویدئویی')),
            ],
            options={
                'verbose_name': 'زمان بندی آزمون ویدئویی',
                'verbose_name_plural': 'زمان بندی\u200c\u200cهای آزمون ویدئویی',
                'db_table': 'course__video_exam_timer',
            },
        ),
        migrations.DeleteModel(
            name='CurrentPDFExamParticipation',
        ),
    ]
