# Generated by Django 5.0.4 on 2024-05-02 10:38

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0015_alter_videocourse_what_we_will_learn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCourseObjectDownloadedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایحاد')),
                ('pdf_course_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.videocourseobject', verbose_name='جزئیات ویدئو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دانلود شده توسط',
                'verbose_name_plural': 'دانلود شده توسط',
                'db_table': 'course__video_course_object_downloaded_by',
            },
        ),
    ]
