# Generated by Django 5.0.4 on 2024-05-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0015_videoexam_videoexamdetail_videoexamresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfexamdetail',
            name='correct_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], help_text='متن یکی از فیلد\u200c\u200cهای بالا', max_length=1, verbose_name='گزینه صحیح'),
        ),
    ]
