# Generated by Django 5.0.4 on 2024-05-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0017_videocourseobject_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourseobject',
            name='download_file_name',
            field=models.CharField(default=1, help_text='ققط انگلیسی', max_length=50, verbose_name='نام فایل دانلودی'),
            preserve_default=False,
        ),
    ]
