# Generated by Django 5.0.4 on 2024-05-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0018_videocourseobject_download_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocourseobjectdownloadedby',
            old_name='pdf_course_object',
            new_name='video_course_object',
        ),
    ]
