# Generated by Django 5.0.4 on 2024-05-10 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0020_alter_pdfexamdetail_correct_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfcourse',
            name='participated_users',
            field=models.ManyToManyField(blank=True, related_name='user_pdf_courses', to=settings.AUTH_USER_MODEL, verbose_name='کاربران ثبت نام شده'),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='participated_users',
            field=models.ManyToManyField(blank=True, related_name='user_video_courses', to=settings.AUTH_USER_MODEL, verbose_name='کاربران ثبت نام شده'),
        ),
    ]
