# Generated by Django 5.0.4 on 2024-05-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0021_alter_pdfcourse_participated_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfcourse',
            name='price_after_discount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت بعد از تخفیف'),
        ),
    ]
