# Generated by Django 5.0.4 on 2024-05-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0022_alter_pdfcourse_price_after_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfcourseobject',
            name='download_file_name',
            field=models.CharField(help_text="فقط حروف انگلیسی، ارقام، '-' و '_'", max_length=50, verbose_name='نام فایل دانلودی'),
        ),
        migrations.AlterField(
            model_name='videocourseobject',
            name='download_file_name',
            field=models.CharField(help_text="فقط حروف انگلیسی، ارقام، '-' و '_'", max_length=50, verbose_name='نام فایل دانلودی'),
        ),
        migrations.AlterField(
            model_name='videocourseobject',
            name='duration',
            field=models.DurationField(default=0, verbose_name='زمان فیلم'),
        ),
    ]
