# Generated by Django 5.0.4 on 2024-04-26 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositslip',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Financial.cart', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='depositslip',
            name='total_cost',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='مبلغ قابل پرداخت'),
        ),
        migrations.AlterField(
            model_name='depositslip',
            name='type',
            field=models.CharField(choices=[('BUY', 'خرید'), ('WAL', 'شارژ کیف پول')], max_length=3, verbose_name='نوع'),
        ),
    ]
