# Generated by Django 5.0.4 on 2024-04-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial', '0003_depositslip_user_alter_depositslip_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositslip',
            name='cart',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='Financial.cart', verbose_name='سبد خرید'),
        ),
    ]
