# Generated by Django 5.0.4 on 2024-04-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial', '0004_alter_depositslip_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositslip',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='آیا رسید معتبر است؟'),
        ),
    ]
