# Generated by Django 5.0.4 on 2024-04-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial', '0005_alter_depositslip_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositslip',
            name='has_been_finished',
            field=models.BooleanField(default=False, editable=False, verbose_name='کارها انجام شده؟'),
        ),
    ]
