# Generated by Django 5.0.4 on 2024-05-06 19:58

import django_ckeditor_5.fields
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='تیتر')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='توضیحات')),
                ('button_text', models.CharField(max_length=30, verbose_name='متن دکمه')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='لینک')),
                ('file', models.FileField(help_text='1300x400', upload_to='Home/HeroBanner/files', verbose_name='فایل')),
                ('can_be_shown', models.BooleanField(default=True, verbose_name='مجوز نشان داده شدن دارد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
            ],
            options={
                'verbose_name': 'هیرو بنر',
                'verbose_name_plural': 'هیرو بنرها',
                'db_table': 'home__intro_banner',
            },
        ),
    ]
