# Generated by Django 5.0.4 on 2024-04-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroBanner',
            new_name='IntroBanner',
        ),
        migrations.DeleteModel(
            name='Banner1',
        ),
        migrations.DeleteModel(
            name='Banner10',
        ),
        migrations.DeleteModel(
            name='Banner2',
        ),
        migrations.DeleteModel(
            name='Banner3',
        ),
        migrations.DeleteModel(
            name='Banner4',
        ),
        migrations.DeleteModel(
            name='Banner5',
        ),
        migrations.DeleteModel(
            name='Banner6',
        ),
        migrations.DeleteModel(
            name='Banner7',
        ),
        migrations.DeleteModel(
            name='Banner8',
        ),
        migrations.DeleteModel(
            name='Banner9',
        ),
        migrations.AlterModelTable(
            name='introbanner',
            table='home__intro_banner',
        ),
    ]
