# Generated by Django 5.0.4 on 2024-04-28 08:59

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_herobanner_introbanner_delete_banner1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='introbanner',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
