# Generated by Django 5.0.4 on 2024-04-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_introbanner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='introbanner',
            name='button_text',
            field=models.CharField(default=1, max_length=30, verbose_name='متن دکمه'),
            preserve_default=False,
        ),
    ]
