# Generated by Django 5.0.4 on 2024-04-21 21:23

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import utils.useful_functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=utils.useful_functions.generate_discount_code, max_length=10, unique=True, verbose_name='کد تخفیف')),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='درصد تخفیف')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='درباره دوره')),
                ('discount_type', models.CharField(choices=[('PU', 'عمومی'), ('PV', 'شخصی')], max_length=2, verbose_name='نوع تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('duration', models.DurationField(help_text='به ثانیه', verbose_name='مدت تخفیف')),
                ('ends_at', models.DateTimeField(editable=False, verbose_name='تاریخ انقضا')),
                ('usage_limits', models.PositiveSmallIntegerField(default=10, verbose_name='محدودیت استفاده به نفر')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیفات',
                'db_table': 'cart__discount_code',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[('PP', 'درکاه پرداخت'), ('CT', 'انتقال به کارت')], max_length=2, null=True, verbose_name='نحوه پرداخت')),
                ('total_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت نهایی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
                'db_table': 'cart__cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('V', 'ویدئویی'), ('B', 'کتابی')], max_length=1, verbose_name='نوع')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Cart.cart')),
                ('pdf_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.pdfcourse', verbose_name='دوره پی\u200cدی\u200cافی')),
                ('video_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.videocourse', verbose_name='دوره ویدئویی')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم\u200cهای سبد خرید',
                'db_table': 'cart__cart_item',
            },
        ),
        migrations.CreateModel(
            name='DiscountCodeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateTimeField(verbose_name='تاریخ استفاده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مورد استفاده کد تخفیف',
                'verbose_name_plural': 'موارد استفاده کد تخفیف',
                'db_table': 'cart__discount_code_user',
            },
        ),
    ]
