# Generated by Django 5.0.4 on 2024-04-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pdf_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Course.pdfcourse', verbose_name='دوره پی\u200cدی\u200cافی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='video_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Course.videocourse', verbose_name='دوره ویدئویی'),
            preserve_default=False,
        ),
    ]
