# Generated by Django 5.0.4 on 2024-04-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositslip',
            name='total_cost',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='مبلغ کل'),
        ),
    ]
