# Generated by Django 5.0.4 on 2024-04-22 09:01

import django.core.validators
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_rename_discount_type_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='ends_at',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='usage_limits',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='محدودیت استفاده به نفر'),
        ),
    ]
