# Generated by Django 5.0.4 on 2024-04-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_rename_course_id_cartitem_course_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت نهایی'),
        ),
    ]
