# Generated by Django 5.0.4 on 2024-04-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cartitem_pdf_course_cartitem_video_course'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pdf_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.pdfcourse', verbose_name='دوره پی\u200cدی\u200cافی'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='video_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.videocourse', verbose_name='دوره ویدئویی'),
        ),
    ]
