# Generated by Django 5.0.4 on 2024-04-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_cartitem_pdf_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='course_pk',
        ),
    ]
