# Generated by Django 5.0.4 on 2024-04-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت نهایی'),
        ),
    ]
