# Generated by Django 5.0.4 on 2024-04-22 09:30

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_alter_discount_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='ends_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ انقضا'),
        ),
    ]
