# Generated by Django 5.0.4 on 2024-04-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_alter_cart_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='type',
            new_name='course_type',
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PP', 'درکاه پرداخت'), ('CT', 'انتقال به کارت')], max_length=2, null=True, verbose_name='نحوه پرداخت'),
        ),
    ]
