# Generated by Django 5.0.4 on 2024-04-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_rename_type_cartitem_course_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='course',
            new_name='cart',
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='به\u200cروز\u200cرسانی شده در تاریخ'),
        ),
    ]
