# Generated by Django 5.0.4 on 2024-04-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_rename_discount_code_discountusage_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.cartitem')),
            ],
        ),
    ]
