# Generated by Django 5.0.4 on 2024-04-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_rename_course_cartitem_cart_alter_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='course_type',
            field=models.CharField(choices=[('V', 'ویدئویی'), ('B', 'کتابی')], max_length=1, verbose_name='نوع'),
        ),
    ]
