# Generated by Django 5.0.4 on 2024-04-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_remove_boughtcourse_total_cost_boughtcourse_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='payment_method',
        ),
    ]
