# Generated by Django 5.0.4 on 2024-04-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_remove_cart_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='course_type',
            field=models.CharField(choices=[('V', 'ویدئویی'), ('B', 'پی\u200cدی\u200cافی')], max_length=1, verbose_name='نوع'),
        ),
    ]
