# Generated by Django 5.0.4 on 2024-04-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_levelone_toplevel_leveltwo_levelthree_levelone_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelone',
            name='level',
        ),
        migrations.RemoveField(
            model_name='leveltwo',
            name='level',
        ),
        migrations.RemoveField(
            model_name='levelthree',
            name='level',
        ),
        migrations.DeleteModel(
            name='TopLevel',
        ),
        migrations.DeleteModel(
            name='LevelOne',
        ),
        migrations.DeleteModel(
            name='LevelThree',
        ),
        migrations.DeleteModel(
            name='LevelTwo',
        ),
    ]
