# Generated by Django 5.0.4 on 2024-04-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_remove_levelone_level_remove_leveltwo_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
