# Generated by Django 5.0.4 on 2024-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_alter_cartitem_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='course_type',
            field=models.CharField(choices=[('VID', 'ویدئویی'), ('PDF', 'پی\u200cدی\u200cافی')], max_length=3, verbose_name='نوع'),
        ),
    ]
