# Generated by Django 5.0.4 on 2024-04-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0012_cart_penalty_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='penalty_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='تعداد دفعات خطا'),
        ),
    ]
