# Generated by Django 5.0.4 on 2024-04-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0014_remove_cart_penalty_count_cart_penalty_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositslip',
            name='is_fake',
            field=models.BooleanField(default=False, verbose_name='آیا رسید فیک است؟'),
        ),
    ]
