# Generated by Django 5.0.4 on 2024-04-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0015_depositslip_is_fake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoughtCourse',
        ),
    ]
