# Generated by Django 5.0.4 on 2024-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0016_delete_boughtcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='ends_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ انقضا'),
        ),
    ]
