# Generated by Django 5.0.4 on 2024-04-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0017_alter_discount_created_at_alter_discount_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositslip',
            name='discount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد تخفیف'),
        ),
    ]
