# Generated by Django 5.0.4 on 2024-04-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0020_alter_discountusage_usage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositslip',
            name='discount_code',
        ),
    ]
