# Generated by Django 5.0.4 on 2024-04-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0024_alter_depositslip_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositslip',
            name='total_cost',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='مبلغ کل'),
        ),
    ]
