# Generated by Django 5.0.4 on 2024-04-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Us', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutView',
            new_name='AboutUs',
        ),
    ]
