# Generated by Django 5.0.4 on 2024-04-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=200, verbose_name='پیام'),
        ),
    ]
