# Generated by Django 5.0.4 on 2024-04-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='bank_card_number',
            field=models.CharField(default=1, max_length=20, verbose_name='شماره کارت'),
            preserve_default=False,
        ),
    ]
