# Generated by Django 5.0.4 on 2024-04-28 07:33

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Us', '0002_rename_aboutview_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to='Us/WhyUs/icons')),
                ('image', models.ImageField(upload_to='Us/WhyUs/images')),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name': 'چرا ما',
                'verbose_name_plural': 'چرا ما',
                'db_table': 'us__why_us',
            },
        ),
    ]
