# Generated by Django 5.0.4 on 2024-04-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Us', '0002_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=250, verbose_name='پیام'),
        ),
    ]
