# Generated by Django 5.0.4 on 2024-04-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Us', '0003_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
    ]
