# Generated by Django 5.0.4 on 2024-04-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Us', '0004_whyus_tab_name_alter_whyus_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whyus',
            name='tab_name',
        ),
        migrations.AlterField(
            model_name='whyus',
            name='icon',
            field=models.ImageField(height_field=64, upload_to='Us/WhyUs/icons', verbose_name='آیکون', width_field=64),
        ),
    ]
