# Generated by Django 5.0.4 on 2024-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Us', '0005_remove_whyus_tab_name_alter_whyus_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whyus',
            name='icon',
            field=models.ImageField(upload_to='Us/WhyUs/icons', verbose_name='آیکون'),
        ),
    ]
